name: pre-commit

on:
  [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: |
          pytypes.txt
          requirements.txt
    - run: pip install mypy -r pytypes.txt -r requirements.txt
    - uses: pre-commit/action@v3.0.1
      with:
          extra_args: --all-files
  unittests:
    runs-on: ubuntu-latest
    needs: pre-commit
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - run: python -m unittest discover -s test -v
